
//STUDENT
###
POST http://127.0.0.1:8000/api/student/save
Content-Type: application/json

{
  "full_name": "sdfsdfs",
  "course": "BSIT",
  "year_level": "4",
  "contact_number": "09152956378",
  "student_status": "Active"
}

###
GET http://127.0.0.1:8000/api/student/getData

###
PUT http://127.0.0.1:8000/api/student/update
Content-Type: application/json

{
  "student_id": "1",
  "full_name": "Gisele Pilar",
  "course": "BSIT",
  "year_level": "4",
  "contact_number": "09452956378",
  "student_status": "Active"
}

###
DELETE http://127.0.0.1:8000/api/student/delete/3





//ATTENDANCE