
//STUDENT
###
POST http://127.0.0.1:8000/api/student/save
Content-Type: application/json

{
  "full_name": "Raesha Manog",
  "course": "BSIT",
  "year_level": "4",
  "contact_number": "09152956378",
  "student_status": "Active"
}

###
GET http://127.0.0.1:8000/api/student/getData

###
PUT http://127.0.0.1:8000/api/student/update
Content-Type: application/json

{
    "student_id": "1",
    "full_name": "franco",
    "course": "BSIT",
    "year_level": 4,
    "contact_number": "09152956378",
    "student_status": "Active"
}

###
DELETE http://127.0.0.1:8000/api/student/delete/1





//ATTENDANCE
###
POST http://127.0.0.1:8000/api/attendance/save
Content-Type: application/json

{
    "student_id": "2",
    "attendance_date": "2026-02-06",
    "attendance_status": "Present",
    "remarks": "very nice"
}

###
GET http://127.0.0.1:8000/api/attendance/get

###
PUT http://127.0.0.1:8000/api/attendance/update
Content-Type: application/json

{
    "attendance_id": "1",
    "student_id": "2",
    "attendance_date": "2026-02-06",
    "attendance_status": "Not Marked",
    "remarks": "bad"
}

###
DELETE http://127.0.0.1:8000/api/attendance/delete/1




